jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node ./lib/index.js

name: Build

on:
  pull_request: ~
  push:
    branches:
      - main
