jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint

name: Lint

on:
  pull_request: ~
  push:
    branches:
      - main
