jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint:md

name: Lint Markdown

on:
  pull_request: ~
  push:
    branches:
      - main
