jobs:
  lint_knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

name: Lint Knip

on:
  pull_request: ~
  push:
    branches:
      - main
