concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
          ref: main
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@77373cfc2535e21149518381cb09e1c04c6068fe # v0.2.2

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
